default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  user: postgres
  timeout: 5000

development:
  <<: *default
  database: parawa_dev

test:
  <<: *default
  database: parawa_test